//
// Generated file, do not edit! Created by nedtool 5.0 from OkToProceed.msg.
//

#ifndef __OKTOPROCEED_M_H
#define __OKTOPROCEED_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0500
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>OkToProceed.msg:19</tt> by nedtool.
 * <pre>
 * //
 * // TODO generated message class
 * //
 * packet OkToProceed
 * {
 * }
 * </pre>
 */
class OkToProceed : public ::omnetpp::cPacket
{
  protected:

  private:
    void copy(const OkToProceed& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const OkToProceed&);

  public:
    OkToProceed(const char *name=nullptr, int kind=0);
    OkToProceed(const OkToProceed& other);
    virtual ~OkToProceed();
    OkToProceed& operator=(const OkToProceed& other);
    virtual OkToProceed *dup() const {return new OkToProceed(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b);

    // field getter/setter methods
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const OkToProceed& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, OkToProceed& obj) {obj.parsimUnpack(b);}


#endif // ifndef __OKTOPROCEED_M_H

