//
// Generated file, do not edit! Created by nedtool 5.0 from Plane.msg.
//

#ifndef __PLANE_M_H
#define __PLANE_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0500
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>Plane.msg:19</tt> by nedtool.
 * <pre>
 * //
 * // TODO generated message class
 * //
 * packet Plane
 * {
 *     int ID;
 *     simtime_t enqueueTimestamp;
 * }
 * </pre>
 */
class Plane : public ::omnetpp::cPacket
{
  protected:
    int ID;
    ::omnetpp::simtime_t enqueueTimestamp;

  private:
    void copy(const Plane& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const Plane&);

  public:
    Plane(const char *name=nullptr, int kind=0);
    Plane(const Plane& other);
    virtual ~Plane();
    Plane& operator=(const Plane& other);
    virtual Plane *dup() const {return new Plane(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b);

    // field getter/setter methods
    virtual int getID() const;
    virtual void setID(int ID);
    virtual ::omnetpp::simtime_t getEnqueueTimestamp() const;
    virtual void setEnqueueTimestamp(::omnetpp::simtime_t enqueueTimestamp);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const Plane& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, Plane& obj) {obj.parsimUnpack(b);}


#endif // ifndef __PLANE_M_H

