//
// Generated file, do not edit! Created by nedtool 5.0 from UpdateRunwayFreed.msg.
//

#ifndef __UPDATERUNWAYFREED_M_H
#define __UPDATERUNWAYFREED_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0500
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>UpdateRunwayFreed.msg:19</tt> by nedtool.
 * <pre>
 * //
 * // TODO generated message class
 * //
 * packet UpdateRunwayFreed
 * {
 * }
 * </pre>
 */
class UpdateRunwayFreed : public ::omnetpp::cPacket
{
  protected:

  private:
    void copy(const UpdateRunwayFreed& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const UpdateRunwayFreed&);

  public:
    UpdateRunwayFreed(const char *name=nullptr, int kind=0);
    UpdateRunwayFreed(const UpdateRunwayFreed& other);
    virtual ~UpdateRunwayFreed();
    UpdateRunwayFreed& operator=(const UpdateRunwayFreed& other);
    virtual UpdateRunwayFreed *dup() const {return new UpdateRunwayFreed(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b);

    // field getter/setter methods
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const UpdateRunwayFreed& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, UpdateRunwayFreed& obj) {obj.parsimUnpack(b);}


#endif // ifndef __UPDATERUNWAYFREED_M_H

