//
// Generated file, do not edit! Created by nedtool 5.0 from UpdatePlaneEnqueued.msg.
//

#ifndef __UPDATEPLANEENQUEUED_M_H
#define __UPDATEPLANEENQUEUED_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0500
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>UpdatePlaneEnqueued.msg:19</tt> by nedtool.
 * <pre>
 * //
 * // TODO generated message class
 * //
 * packet UpdatePlaneEnqueued
 * {
 * }
 * </pre>
 */
class UpdatePlaneEnqueued : public ::omnetpp::cPacket
{
  protected:

  private:
    void copy(const UpdatePlaneEnqueued& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const UpdatePlaneEnqueued&);

  public:
    UpdatePlaneEnqueued(const char *name=nullptr, int kind=0);
    UpdatePlaneEnqueued(const UpdatePlaneEnqueued& other);
    virtual ~UpdatePlaneEnqueued();
    UpdatePlaneEnqueued& operator=(const UpdatePlaneEnqueued& other);
    virtual UpdatePlaneEnqueued *dup() const {return new UpdatePlaneEnqueued(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b);

    // field getter/setter methods
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const UpdatePlaneEnqueued& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, UpdatePlaneEnqueued& obj) {obj.parsimUnpack(b);}


#endif // ifndef __UPDATEPLANEENQUEUED_M_H

